---
output: 
   html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 3
    number_sections: false
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# tmaptools::palette_explorer()
```

# Zambia hotspots

Climate-conflict intersection hotspots in Zambia

```{r k3, echo=FALSE, message=F, warning=F,comment=F}
library(terra)
library(tmap)
library(mapview)
root <- 'D:/OneDrive - CGIAR/Analysis/CSO/'
iso <- 'ZMB'

conf <- geojsonio::geojson_sf(paste0(root,iso,'/ZMB_megapixels.geojson'))
hconf <- conf[conf$conflict_clust_label=="High conflict"  ,]
mconf <- conf[conf$conflict_clust_label=="Moderate conflict"  ,]
lconf <- conf[conf$conflict_clust_label=="Limited conflict"  ,]
k  <- unique(hconf$intersect_conf_clim)
km <- unique(mconf$intersect_conf_clim)
kl <- unique(lconf$intersect_conf_clim)
#k <- c(k[3],k[1],k[2])

for(i in 1:length(k)){
  hconf$clust[hconf$intersect_conf_clim==k[i]] <- i
}
#labs <- conf$intersect_conf_clim[!duplicated(conf$clust)]
labs <- gsub(" levels of| values of|\\[|/.*", "", k)

for(i in 1:length(km)){
  mconf$clust[mconf$intersect_conf_clim==km[i]] <- i
  lconf$clust[lconf$intersect_conf_clim==kl[i]] <- i
}
labsm <- gsub(" levels of| values of|\\[|/.*", "", km)
labsl <- gsub(" levels of| values of|\\[|/.*", "", kl)

hconf$clust <- as.factor(hconf$clust)
bdy1 <- geodata::gadm(country=iso, level=1, path=paste0(root,iso,'/'))
bdy1 <- sf::st_as_sf(bdy1)
bdy1 <- sf::st_cast(bdy1) # Removes duplicte labels
bdy2 <- geodata::gadm(country=iso, level=2, path=paste0(root,iso,'/'))
bdy2 <- sf::st_as_sf(bdy2) 
bdy2 <- sf::st_cast(bdy2)
#bdy3 <- geodata::gadm(country=iso, level=3, path=paste0(root,iso,'/'))
#bdy3 <- sf::st_as_sf(bdy3)
library(sf)

reName <- function(hconf){
  hconf <- st_intersection(hconf,bdy2[c("NAME_1","NAME_2")])
  hconf$Province <- hconf$NAME_1
  hconf$District <- hconf$NAME_2
  names(hconf)[7] <- 'Fatalities' 
  names(hconf)[names(hconf)=="climvar_medn_prec"] <- "Average Rainfall"
  names(hconf)[names(hconf)=="pop"] <- "Population"
  names(hconf)[names(hconf)=="awe"] <- "Absolute Wealth Index"
  return(hconf)
}
hconf <- reName(hconf)
mconf <- reName(mconf)
lconf <- reName(lconf)


tmap_mode("view")
ken <- tm_shape(bdy1, name = 'Province')+
  tm_borders() +
  tm_shape(bdy2, name = 'District')+
  tm_borders() +
  #tm_shape(bdy3, name = 'Ward')+
  #tm_borders()+
  tm_shape(hconf, name = 'High Conflict')+
  tm_fill(col= "clust", palette="-YlOrRd", title = 'High-Conflict-Hotspots', labels=labs, popup.vars=c("Province","District", "Fatalities", "Average Rainfall", "Population", "wasting","female_ed", "male_ed", "Absolute Wealth Index", "migration"))+
  tm_shape(mconf, name = 'Moderate Conflict')+
  tm_fill(col= "clust", palette="-YlOrBr", title = 'Moderate-Conflict-Hotspots', labels=labsm, popup.vars=c("Province","District", "Fatalities", "Average Rainfall", "Population", "wasting","female_ed", "male_ed", "Absolute Wealth Index", "migration"))+
  tm_shape(lconf, name = 'Limited Conflict')+
  tm_fill(col= "clust", palette="-Greens", title = 'Limited-Conflict-Hotspots', labels=labsl, popup.vars=c("Province","District", "Fatalities", "Average Rainfall", "Population", "wasting","female_ed", "male_ed", "Absolute Wealth Index", "migration"))+
  tm_view(view.legend.position =c("right", "top"))+
  tm_layout(legend.stack="vertical")+
  tm_format("World")
ken #Conflict Severity


# tmap_mode("plot")
# ken <- tm_shape(bdy1, name = 'Department')+
#   tm_borders(col='black') +
#   tm_text("NAME_1", size = 1, remove.overlap = TRUE)+ 
#   #tm_shape(bdy2, name = 'Municipality')+
#   #tm_borders() +
#   #tm_shape(bdy3, name = 'Ward')+
#   #tm_borders()+
#   tm_shape(conf, name = 'Conflict')+
#   tm_fill(col= "clust", palette="-YlOrRd", alpha=0.65, title = 'Climate-conflict hotspots', labels=labs)+
#   tm_compass(type = "8star", position = c("right", "top")) +
#   tm_scale_bar(breaks = c(0, 50, 100), text.size = 1, 
#                position = c("right", "bottom"))+
#   tm_layout(legend.outside=F,
#             legend.width = 0.75,
#             legend.title.size= 1.3,
#             legend.text.size = 1.1,
#             legend.frame=F,
#             legend.just = c("left", "top"),
#             legend.position= c("left", "top"))
# ken 
# 
# 
# tmap_save(ken,  dpi= 600,  height=8, width=10, units="in",
#           filename=paste0(root,iso,'/',iso,"_High_confict_climate_intersection.png"))

```


